[project]
name = "xfmr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "numpy>=2.5.3",
    "protobuf>=7.36.1",
    "sacrebleu>=2.6.0",
    "sentencepiece>=0.2.2",
    "spacy>=3.8.16",
    "tiktoken>=0.14.0",
    "tokenizers>=0.23.2",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[project.scripts]
xfmr2017 = "xfmr.xfmr2017:main"


[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-html>=4.2.0",
    "ruff>=0.16.7",
]
